# Generated by Django 3.2.3 on 2022-02-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='languageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('EN', 'English'), ('PO', 'Polish'), ('SW', 'Swahili'), ('AA', 'Afrikaans'), ('EL', 'Greek'), ('AR', 'Arabic'), ('ES', 'Spanish'), ('IT', 'Italian'), ('KI', 'Gikuyu'), ('KO', 'Korean'), ('ML', 'Malayalam'), ('MN', 'Mongolian'), ('RU', 'Russian')], default='EN', help_text='Books Language', max_length=2)),
            ],
        ),
    ]
