# Generated by Django 3.2.3 on 2022-02-27 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_bookinstance_borrower'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='summary',
            field=models.TextField(default='Genre about this World issues', help_text='Enter a brief description of the genre', max_length=1000),
        ),
    ]
