# Generated by Django 3.2.3 on 2022-02-27 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_genre_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.OneToOneField(help_text='Book Language', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.language'),
        ),
    ]
